### ISSUE TITLE
GW client doesn't detect dx11, only dx9.

### ISSUE THREAD

**Issue by user101246** [asmaloney/GuildWars2-macOS#1]
I followed your tutorial on a Mac mini m2 and the games does work. It even performs better than on parallel.
However, I can't get the GW client to detect dx11.

Things that I have done different than your tutorial were:
- I installed Wineskinserver manually
- used engine WS11WineCX64Bit22.1.0.rc2
- installed dxvk1103 and dxvk master ( there are no dxvk with _macOs in their name) 

As I mentioned earlier, GW client only shows the option for dx9 rendering and not dx11.
<img width="599" alt="Screenshot 2023-04-01 at 15 18 36" src="https://user-images.githubusercontent.com/129601663/229291435-ea24c929-4e36-4b93-8aba-624fb277ab0b.png">

**Comment by asmaloney** [comment]
DX11 is now the default for GW2, so you should be able to just uncheck "Enable DX9 Rendering (Deprecated)" and you'll be using it. (In fact they are going to remove the DX9 option entirely soon.)

Does it still work after you've done that? I don't know how/if GW2 works on Apple processors since I don't have one.

**Comment by user101246** [comment]
after disabling it, it runs much smoother. I am having the frame rate limiter at 60 to avoid any heating with no issues what so ever.

**Comment by asmaloney** [comment]
Praise Joko! Thanks for reporting it.

I've updated the post to make it clear to disable this DX9 option since DX11 is the default.
