### ISSUE TITLE
Installing GW2

### ISSUE THREAD

**Issue by arsenicxx** [asmaloney/GuildWars2-macOS#5]
### macOS Version

macOS Ventura 13.3.1

### WineskinServer Version

2.9.1.9

### Wine Engine Version

WS11WineCX64Bit22.1.1-rc2

### Problem

Hello!

I've previously played GW2 following your instructions, but the game suddenly would not launch so I'm attempting a re installation. As I've been following your guidelines for installing GW2, I've been successful with installing Wineskin again, however now when I attempt to install Guild Wars 2 itself with the file from ArenaNet, I am unable to do it as my Mac will tell me I can't extract it using what I have (The Unarchiver). Is there a workaround for this as I have been seeing that .exe does not work on Mac?

So sorry if this is a silly question. I'm just very stuck!

Thanks so much in advance.

**Comment by asmaloney** [comment]
> but the game suddenly would not launch

If you still have that installation, you can probably get it to run using the `-usecoherent` command line option which is required for now since CEF does not work with WINE. See the updated post in the **Setting Up The Environment** section.

> when I attempt to install Guild Wars 2 itself with the file from ArenaNet, I am unable to do it as my Mac will tell me I can't extract it using what I have

That sounds like you are double-clicking the GW-2 installer exe which isn't what you do. You should be selecting the installer using _Choose Setup Executable_ (see the **Installing Guild Wars 2** section).

**Comment by asmaloney** [comment]
Please reopen with details if you're still not able to get it installed.
